#!/bin/sh

# ci_post_clone.sh
# Generates Config.swift from environment variable for Xcode Cloud builds

set -e

echo "Generating Config.swift from environment variable..."

# Determine repository root (script is in ci_scripts/ subdirectory)
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
CONFIG_FILE="${REPO_ROOT}/Weather2045/Config.swift"

if [ -z "$OPENWEATHERMAP_API_KEY" ]; then
    echo "Error: OPENWEATHERMAP_API_KEY environment variable is not set"
    exit 1
fi

cat > "$CONFIG_FILE" << EOF
import Foundation

/// Configuration file for API keys and secrets
/// Generated by ci_post_clone.sh during Xcode Cloud build
enum Config {
    /// OpenWeatherMap API Key
    static let openWeatherMapAPIKey = "$OPENWEATHERMAP_API_KEY"
}
EOF

echo "Config.swift generated successfully at $CONFIG_FILE"
